name: Terraform Plan

on:
  workflow_call:
    inputs:
      tf_version:
        type: string
        required: false
        default: "1.6.6"
      working_directory:
        description: "Where to run terraform init/validate/plan (e.g. env/prod)"
        type: string
        required: true

    secrets:
      DO_TOKEN:
        required: true
      SPACES_ACCESS_KEY_ID:
        required: true
      SPACES_SECRET_ACCESS_KEY:
        required: true

permissions:
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Terraform fmt (check)
        run: terraform fmt -check -diff -recursive

      - name: Terraform init
        working-directory: ${{ inputs.working_directory }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: "true"
        run: terraform init -input=false

      - name: Terraform validate
        working-directory: ${{ inputs.working_directory }}
        env:
          TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
        run: terraform validate

      - name: Terraform plan
        working-directory: ${{ inputs.working_directory }}
        env:
          TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
        run: terraform plan -input=false -no-color
